apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-deployment
spec:
  selector:
    matchLabels:
	      app: cloud-job
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
	       app: cloud-job
    spec:
      containers:
      - name: cloud-job
	      image: vibhore68/cloud-job:v1.9
	      imagePullPolicy: Always
	      ports:
	      - containerPort: 80
