apiVersion: v1
kind: Service
metadata:
  name: cloud-service
  labels:
    app: cloud-job
spec:
  selector:
    app: cloud-job
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31200
